### PR TITLE
Move to Base64 for AuthenticationTokens

### PR DESCRIPTION
**Pull request by advaithm**
Why?
Base64 is more readable for humans allowing people using inncryption to understand and identify errors. For octii this allows us to simplify some aspects of octii for 3rd party clients.

### CODE REVIEW

**Comment by lleyton** [comment]
LGTM

@joelinnatical thoughts?

**Comment by lleyton** [comment]
@advaithm It looks like the btoa dependency is not being used anymore, might want to remove that

**Comment by advaithm** [comment]
Ah my bad. I will fix it

**Review by joelinnatical — CHANGES_REQUESTED** [review]
Good idea. I have two notes, one requires changes before merge.
1. Refactor the `arrayBufferToBase64` to use functional primitives (such as `map`) instead of the current variable soup. (requires changes before merge)
2. Remove `authenticationTokenLegacy` from the `Keychain` type and the legacy functions before deploying to production. (They can stay for now, as I assume they'll be needed in Octii for the time being, right @lleyton?)

**Comment by advaithm** [comment]
the `authenticationTokenLegacy` value is there for migration from the old method to the new one

**Review by joelinnatical — APPROVED** [review]
LGTM

**Review by lleyton — APPROVED** [review]
LGTM

**Pull request merged**
